apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersystem-deployment
  namespace: jihyeon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ordersystem
  template:
    metadata:
      labels:
        app: my-ordersystem
    spec:
      containers:
      - name: my-ordersystem
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/jihyeon/ordersystem:latest
        ports:
        - containerPort: 8080
        env:
        # 아래의 name과 yml의 ${}의 변수명과 일치해야함
        - name: DB_HOST
          valueFrom: 
            secretKeyRef:
              name: ordersystem-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom: 
            secretKeyRef:
              name: ordersystem-secrets
              key: DB_PW
        # 컨테이너 상태 확인을 통해 롤링업데이트 최적화 
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /health
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ordersystem-service
  namespace: jihyeon
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: my-ordersystem