server:
  port: 8080

# eureka 위치 설정
eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: api-gateway
    
#  라우터 설정
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              # - 'http://localhost:3000'
              - 'http://www.jihyeon.shop'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true
      routes:
        - id: member-service
          predicates:
            - Path=/member-service/**
          filters:
            # 첫 번째 접두어(member-service)를 제거한 후에 member-service 서버로 http 요청 전달
            - StripPrefix=1
          # eureka에 등록된 member-service 라는 이름으로 http 요청 전달
          # member의 yml 파일에 있는 spring.application.name 과 매핑

          # eureka에 등록된 이름이 아닌, k8s의 서비스명을 배포시 사용
          uri: http://member-service

        - id: ordering-service
          predicates:
            - Path=/ordering-service/**
          filters:
            - StripPrefix=1
          uri: http://ordering-service

        - id: product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
          uri: http://product-service

jwt:
  expirationAt: 10000
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  expirationRt: 10000
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5