server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    activate:
      on-profile: local
  application:
    name: product-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordermsa
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true

  kafka:
    kafka-server: localhost:9092
    consumer:
      # group-id는 consumer group을 식별하는 id 로서 동일한 group id 를 가진 consumer 들은 message를 분담해서 consume
      # 그런데 만약 consumer가 서로 다른 group id를 가지고 한 topic을 consume 하면 message를 각기 수신하는 pub/sub 효과 발생
      group-id: product-group
      # earliest : 가장 처음 들어온 메세지부터 읽기 시작
      # latest : 현 시점 이후 들어오는 메세지만 읽음
      auto-offset-reset: earliest

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

    properties:
      hibernate:
        format-sql: true

  output:
    ansi:
      enabled: always

cloud:
  aws:
    credentials:
      access-key: xx
      secret-key: yy
    region:
      static: ap-northeast-2
    s3:
      bucket: jihyeon-bucket1234